### PR TITLE
DBC22-1484: Added weather models and API endpoints

### PR DESCRIPTION
**Pull request by bcgov-brwang**
DBC22-1484: Added weather models and API endpoints

Created API endpoint <hostname>/api/weather/regional for retrieving areas regional current conditions and forecasts.

Local test URL:

http://localhost:8000/api/weather/regional

Please add the following variables in .env for accessing SAWSx API.

DRIVEBC_WEATHER_API_BASE_URL=https://sawsx-services-dev-api-gov-bc-ca.test.api.gov.bc.ca/api/v1/ec/cityforecast/
DRIVEBC_WEATHER_API_TOKEN_URL=https://dev.loginproxy.gov.bc.ca/auth/realms/apigw/protocol/openid-connect/token/
WEATHER_CLIENT_ID=<your client id>
WEATHER_CLIENT_SECRET=<your client secret>
DRIVEBC_WEATHER_AREAS_API_BASE_URL=https://sawsx-services-dev-api-gov-bc-ca.test.api.gov.bc.ca/api/v1/ec/list/fcstareas

### CODE REVIEW

**Comment by ray-oxd** [comment]
I can't test this at the moment - getting {'error': 'Error obtaining access token: 400 Client Error: Bad Request for url: https://dev.loginproxy.gov.bc.ca/auth/realms/apigw/protocol/openid-connect/token/'}. Do we have a public/production endpoint I can access without VPN?

Also, can we store location as one pointfield instead of separate string columns? Storing it like this prevents any kind of spatial queries, and also further transformation is required before our FE can make use of it.

**Comment by bcgov-brwang** [comment]
> I can't test this at the moment - getting {'error': 'Error obtaining access token: 400 Client Error: Bad Request for url: [https://dev.loginproxy.gov.bc.ca/auth/realms/apigw/protocol/openid-connect/token/'}](https://dev.loginproxy.gov.bc.ca/auth/realms/apigw/protocol/openid-connect/token/'%7D). Do we have a public/production endpoint I can access without VPN?
> 
> Also, can we store location as one pointfield instead of separate string columns? Storing it like this prevents any kind of spatial queries, and also further transformation is required before our FE can make use of it.

I tried this endpoint without connecting VPN and it works. Probably it was caused by the client id and client secret. This token endpoint comes from dev keycloak server, so we still have no endpoints from production yet.
Here are the client id/secret you can have a try when you test.

WEATHER_CLIENT_ID=22ACAA73-BC8B6A86C73
WEATHER_CLIENT_SECRET=aeadbb3b-4418-4499-b31b-908f36e53076

I will look into if we can use pointfield as location storage. Thanks.

**Comment by ray-oxd** [comment]
Thanks @bcgov-brwang, please ping one of the devs to message me on Slack when it's ready again.

I've copied the ID and secret, please remove/edit them out of your previous comment.

**Comment by bcgov-brwang** [comment]
> Thanks @bcgov-brwang, ping one of the devs to message me on Slack when it's ready again.
> 
> I've copied the ID and secret, please remove/edit them out of your previous comment.

I've updated the model to use PointField for location, but I kept two columns location_latitude and location_longitude in the database. These columns won't be returned in the response, just make it easy to populate the location point and keep the tracking if any issues, because the original value returned from SAWSx api for latitude and longitude are something like this "51.65N" and "120.03W". Thanks.

**Review by fatbird — APPROVED** [review]

**Pull request merged**
