### PR TITLE
Feature/dbc22 928

### PR DESCRIPTION
**Pull request by bcgov-brwang**
This PR created Advisory model and api endpoint for consumption from the frontend.
It also enabled the capability of view revision, basic preview, and scheduled publishing.
API endpoint: http://localhost:8000/api/cms/advisories

### CODE REVIEW

**Review by ray-oxd — CHANGES_REQUESTED** [review]
Please run manage.py makemigrations and check in the migration.

**Comment by bcgov-brwang** [comment]
> Please run manage.py makemigrations and check in the migration.
Done

**Review by ray-oxd — CHANGES_REQUESTED** [review]
PR looks great but please do the following polishing:
- rename columns to not have advisory_ prefix
- Add CMS features to bottom button/panel

**Comment by bcgov-brwang** [comment]
> PR looks great but please do the following polishing:
> 
> * rename columns to not have advisory_ prefix
> * Add CMS features to bottom button/panel

Done

**Review by ray-oxd — CHANGES_REQUESTED** [review]
Please fix all unit tests and use assert instead of self.assertTrue etc.

**Review by ray-oxd — DISMISSED** [review]

**Comment by ray-oxd** [comment]
Note that we'll have to update the serializer tests too if we exclude those fields in the future (see last commit, 'depth' 'slug' etc.)

**Review by ray-oxd — APPROVED** [review]

**Review by ray-oxd — APPROVED** [review]

**Review by ray-oxd — DISMISSED** [review]

**Comment by ray-oxd** [comment]
Closed, replaced with https://github.com/bcgov/DriveBC.ca/pull/106

**Pull request closed without merging**
