### PR TITLE
DBC22-2905: centered the map only for the first loading when advisories are available

### PR DESCRIPTION
**Pull request by bcgov-brwang**
DBC22-2905: centered the map only for the first loading when advisories are available

The fix moved the logic of the center map to an useEffect hook that only can be executed for the first loading, to avoid the behavior that center the map when the user panning or zooming in/out.

Jira: https://moti-imb.atlassian.net/browse/DBC22-2905

### CODE REVIEW

**Comment by ray-oxd** [comment]
Per comments in [DBC22-2532](https://moti-imb.atlassian.net/browse/DBC22-2532), this part of the requirement is not finished:

#For maximizing panels we do either, but the first option is preferred over the second:

#In mobile, when the panel is maxed out, it should show the same advisories as the previously half opened state.

#Prevent maximizing advisory panel in mobile, but make sure we allow scrolling

**Comment by bcgov-brwang** [comment]
Disabled maximizing advisory panel on mobile view due to the difficulty to sync the advisory list when the panel is maximized.

**Review by ray-oxd — CHANGES_REQUESTED** [review]
Please make sure only advisories panels are locked from maximizing.

**Comment by bcgov-brwang** [comment]
> Please

Put a condition on advisory panel when maximizing.
https://github.com/bcgov/DriveBC.ca/pull/676/commits/2d963d6728dc191b76494e14d916bd1dcebcee2a

**Review by ray-oxd — APPROVED** [review]

**Pull request merged**
